### ISSUE TITLE
源代码参考的厉害

### ISSUE THREAD

**Issue by Motor-taxi-master-rider** [denglj/aiotutorial#4]
代码基本就是https://github.com/aosabook/500lines/tree/master/crawler/code这里guido写得啊，参考不等于改个函数名就全部拿过来吧？

**Comment by denglj** [comment]
请看清楚为按我的思路讲解异步编程所简化与改善之处。

《李白诗词赏析》的作者太可恶了，抄袭了李白的全部诗词。

**Comment by ResolveWang** [comment]
哈哈哈，支持作者。开始没认真读的时候，我也觉得是抄袭和翻译，但仔细品味下来，却发现开始的想法很片面。
